/**
 * Restaurant.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomerViewModel } from './customerViewModel';
import { RestaurantTableViewModel } from './restaurantTableViewModel';

export interface ReservationViewModel { 
    id?: number;
    startTime?: Date;
    endTime?: Date;
    table?: RestaurantTableViewModel;
    customer?: CustomerViewModel;
}